### ISSUE TITLE
Update parachain-template tutorials to use `polkadot-omni-node`

### ISSUE THREAD

**Issue by iulianbarbu** [polkadot-developers/polkadot-docs#176]
We aim to make [polkadot-omni-node](https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/reference_docs/omni_node/index.html) the go to node for running the `parachain-template` runtime and for other compatible parachains in the ecosystem. 

We've made a few changes to the `parachain-template` README to account for various ways of starting it for local development, including with `polkadot-omni-node` (based on zombienet), which should be the preferred choice. All these changes and things they reference will be released with `stable2412` in December, but by that time a release candidate will be done which will be very close to what `stable2412` will be (I'll follow up here once the release candidate is out).

Current `polkadot-sdk` master branch contains the latest state of the tooling (e.g. chain-spec-builder, frame-omni-bencher) & `parachain-template`, while [polkadot-sdk-parachain-template](https://github.com/paritytech/polkadot-sdk-parachain-template) repo will be synced with `polkadot-sdk`'s `parachain-template` after `stable2412`. 

I scanned a bit the docs on this repo and I found [this](https://github.com/polkadot-developers/polkadot-docs/blob/master/tutorials/polkadot-sdk/build-a-parachain/connect-a-parachain.md#prepare-the-parachain-collator) tutorial which should be updated to use `polkadot-omni-node` instead of `parachain-template-node`. There might be other similar places where such an update makes sense.

All in all, I think we should start working on the required changes after the release candidate is out (will follow up soon about it) and communicate here about things that aren't working (given the docs) if any.

**Comment by kianenigma** [comment]
cc @CrackTheCode016
